@baseUrl = http://localhost:3001
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZTA5YWIzZi05MTcwLTRlOGEtYjE1Zi03ZDhlNDU0NjRjYzIiLCJpYXQiOjE3NzM5OTc4MTcsImV4cCI6MTc3NDAwMTQxN30.BEGC-43-Gl9aX1IV9exsO79D8GA6kPMhOf78CIk_tdc

### Register with valid informations
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123",
  "confirm": "Password123",
  "username": "testuser"
}

### Register with wrong informations
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test",
  "password": "test",
  "username": "test"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123"
}

### Login with wrong email
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "testFalseEmail",
  "password": "Password123"
}

### Logout 
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Cookie: accessToken={{accessToken}}