@baseUrl = http://localhost:3000

// TODO : ajouter les tests pour les requêtes invalides quand le controller sera à jour pour les gérer

### Get user's library
GET {{baseUrl}}/library
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWI5OTI1MS05NTNkLTQ4ZGYtYWFiMi1jMzBkMDJmMjBjODMiLCJpYXQiOjE3NzM4NDAyOTgsImV4cCI6MTc3Mzg0Mzg5OH0.QBE8WVYizKgS2pqUwPEVSBoA8wFp5O3gbOjjOD3bE8E


### Add a book to a user's library
POST {{baseUrl}}/library
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWI5OTI1MS05NTNkLTQ4ZGYtYWFiMi1jMzBkMDJmMjBjODMiLCJpYXQiOjE3NzM4NDAyOTgsImV4cCI6MTc3Mzg0Mzg5OH0.QBE8WVYizKgS2pqUwPEVSBoA8wFp5O3gbOjjOD3bE8E

{
  "isbn": "9782070368228",
  "openLibraryId": "OL45804W",
  "title": "L'Étranger",
  "author": "Albert Camus",
  "genre": "Roman",
  "description": "Un classique de la littérature française du XXe siècle.",
  "thumbnail": "https://covers.openlibrary.org/b/id/8231856-L.jpg",
  "publisher": "Gallimard",
  "pageCount": 185,
  "language": "fr",
  "publishedYear": 1942,
  "status": "TO_READ"
}

### Update reading status of a book in user's library
PATCH {{baseUrl}}/library/bdae862b-0ec5-4371-9977-b81b6889179e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWI5OTI1MS05NTNkLTQ4ZGYtYWFiMi1jMzBkMDJmMjBjODMiLCJpYXQiOjE3NzM4NDAyOTgsImV4cCI6MTc3Mzg0Mzg5OH0.QBE8WVYizKgS2pqUwPEVSBoA8wFp5O3gbOjjOD3bE8E

{
  "status": "READING"
}

### Delete a book from user's library
DELETE {{baseUrl}}/library/bdae862b-0ec5-4371-9977-b81b6889179e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWI5OTI1MS05NTNkLTQ4ZGYtYWFiMi1jMzBkMDJmMjBjODMiLCJpYXQiOjE3NzM4NDAyOTgsImV4cCI6MTc3Mzg0Mzg5OH0.QBE8WVYizKgS2pqUwPEVSBoA8wFp5O3gbOjjOD3bE8E